twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['base_theme.html.twig']
#    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/emails/css': email_css
        '%kernel.project_dir%/emails/templates': email_templates
    date:
        format: 'd M, Y g:i A'
        timezone: 'Europe/Paris'

when@test:
    twig:
        strict_variables: true
