<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'c0333e50cf32cb4a516da221abd5d523',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/chakhguereevdev?serverVersion=10.4.28-MariaDB',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'AUTH0_CLIENT_ID' => 'Py962KnC5y0jEvCK68ybAwoyJLzir3g9',
  'AUTH0_DOMAIN' => 'https://dev-2hpu-3au.eu.auth0.com',
  'AUTH0_CLIENT_SECRET' => 'XRRFFA-jYIey78GjR9HKgYW4M_KUq5EgJSUIXq8rj-wa5DxyPz5xrz9hOPaaJGXH',
  'AUTH0_COOKIE_SECRET' => '5c4f5e6bff76139df5bab51a58b93777cdf6a448f640109a9f10a34da24dc1ce',
  'AUTH0_BASE_URL' => 'https://atelier-electronik.com/public/index.php/home',
  'AUTH0_MANAGEMENT_TOKEN' => 'you',
  'AUTH0_AUDIENCE' => 'youraudience',
  'LOGIN_REDIRECT_URI' => 'https://atelier-electronik.com/public/index.php/home',
);
