<?php

namespace ContainerKNxYphu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHommeUltimeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HommeUltimeController' shared autowired service.
     *
     * @return \App\Controller\HommeUltimeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'HommeUltimeController.php';

        $container->services['App\\Controller\\HommeUltimeController'] = $instance = new \App\Controller\HommeUltimeController();

        $instance->setContainer(($container->privates['.service_locator.wwLu14F'] ?? $container->load('get_ServiceLocator_WwLu14FService'))->withContext('App\\Controller\\HommeUltimeController', $container));

        return $instance;
    }
}
