<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKzlWGz0\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKzlWGz0/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKzlWGz0.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKzlWGz0\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKzlWGz0\App_KernelProdContainer([
    'container.build_hash' => 'KzlWGz0',
    'container.build_id' => '7a1b87e8',
    'container.build_time' => 1685974621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKzlWGz0');
