<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHeDJmex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHeDJmex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHeDJmex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHeDJmex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHeDJmex\App_KernelDevDebugContainer([
    'container.build_hash' => 'HeDJmex',
    'container.build_id' => '65e8db77',
    'container.build_time' => 1688143781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHeDJmex');
